import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import '../../data/connection/environments.dart';
import 'firebase_options_dev.dart' as dev;
import 'firebase_options_prod.dart' as prod;

// Per-flavor files are generated by the FlutterFire CLI, e.g. for dev:
//   flutterfire config --project=ts-drivers-dev \
//     --out=lib/app/core/services/firebase/firebase_options_dev.dart \
//     --android-package-name=com.transport_system.ts_driver.dev \
//     --ios-bundle-id=com.transportsystemgroup.tsdrivers.dev
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => switch (Environment.current) {
        Environment.dev => dev.DefaultFirebaseOptions.currentPlatform,
        // staging ships dev's bundle id / google-services.json natively, so Dart
        // must initialize the same project or the two disagree at runtime.
        // firebase_options_staging.dart is kept for when staging gets its own
        // push registration back — see flavorizr.yaml.
        Environment.staging => dev.DefaultFirebaseOptions.currentPlatform,
        Environment.production => prod.DefaultFirebaseOptions.currentPlatform,
      };
}
